### ISSUE TITLE
 Print new line on IDE

### ISSUE THREAD

**Issue by nsathiya** [mark-archer/hostlang#3]
```
type Node: fields val[int]=0 next[Node]=null

fn sumOfLinkedList(head) 
	var sum : 0
	var current : head
	while (!= current null)
		set sum (+ sum current.val)
		set current current.next

	log sum	

var head : new Node val=5
set head.next (new Node val=7)
set head.next.next (new Node val=3)

sumOfLinkedList head

;; remove node
set head.next head.next.next

sumOfLinkedList head
```
The above only prints "8", as opposed to "15 \n 8". The output from second sumOfLinkedList function prints over the first one. This is also the case for any log. Should this be solved in IDE?

**Comment by mark-archer** [comment]
`log` outputs it's arguments to the console.  And when I run the above code I do see 15 and 8 output as well as a lot of other things.  If you want to output data to the results pane in the IDE you can use `cout`.

**Comment by mark-archer** [comment]
I should probably explain `>>` as well as `_` some more.  The symbol `_` always holds the result of the last statement executed.  For example:
```
+ 1 2
; _ equals 3

+ _ 3
; _ now equals 6
```

The `>>` function builds on this.  It's really an instruction for the parser.  When the parser sees this it parses the next function with `_` as the first argument.
```
; so this
>> * 3
; gets parsed as this
* _ 3

; and therefore this
+ 1 2
>> * 3
; produces 6
; and can be thought of as this
* (+ 1 2) 3
```

The `_` variable and `>>` operator make it so people can break nested function calls into sequences of calls without having to declare and reference variables.  This is a core idea in Host and, I think, a very nice way to code.

**Comment by nsathiya** [comment]
Yes, when I run it in the shell, it prints (with warnings- [ 'getType -- encountered an id for an unknown type', 'Node' ]) but on the IDE it only prints one value. I believe the old value is re-written.
Im using a mac btw. 
<img width="885" alt="screen shot 2017-06-01 at 10 43 17 pm" src="https://cloud.githubusercontent.com/assets/1971844/26712625/a4e45034-471c-11e7-8ce0-74895aedf492.png">

**Comment by mark-archer** [comment]
When I change the line `log sum` to `cout sum` it prints `15` then `8` then `null`.  Are you not seeing this?

The IDE only prints out the last value returned automatically.  If you want to explicitly print out something in the middle of execution you use `cout`.  The results pane is considered distinct from the console.  This is the view I have on windows (notice the console on the right):
![image](https://cloud.githubusercontent.com/assets/5472995/26733603/2e61c212-4770-11e7-9ef0-125b7ae893e0.png)

**Comment by nsathiya** [comment]
Ah I didn't read the part about cout prints to IDE and log is for console. Thanks it does work now!

**Comment by mark-archer** [comment]
`cout` should probably be changed to `print` or something a little more idiomatic of host
