### ISSUE TITLE
new types throwing warnings

### ISSUE THREAD

**Issue by mark-archer** [mark-archer/hostlang#4]
`type` creates a new type (e.g. `type Person`) and should add it to the list of known types but when the new type is referenced (e.g. `var p : new Person`) `getType` throws a warning about `Person` being an unknown type.  

This is probably an easy fix.  Either `getType` doesn't have the correct reference to the list of known types or `type` isn't adding the new type to the list of known types after creating it.

**Comment by nsathiya** [comment]
yes, can duplicate warning- 

[ 'getType -- encountered an id for an unknown type', 'Node' ]
